delete from CANDIDATURE;
delete from FICHEDEPOSTE;
delete from DEMANDECOMPETENCE;
delete from EQUIPE;
delete from COLLABORATEUR;
delete from CANDIDAT;
delete from COMPETENCE;

/*
 Compétences
 */
insert into COMPETENCE(NOMCOMPETENCE) values ('Java');
insert into COMPETENCE(NOMCOMPETENCE) values ('Regex');
insert into COMPETENCE(NOMCOMPETENCE) values ('Javas cool');
insert into COMPETENCE(NOMCOMPETENCE) values ('Microsoft Word');
/*
 CANDIDATS
 */
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Edmond','Fyon',0,1);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Bob','Marlex',1,2);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Didier','Tripoo',0,4);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Quentin','Beaussart',0,4);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Dimitri','Calmels',0,1);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Xavier','Fernandez',0,1);
insert into CANDIDAT(PRENOMCANDIDAT,NOMCANDIDAT,FEUXVERTCODIR,COMPETENCES) values ('Nathan','Dias',0,3);

/*
 COLLABORATEURS
 */
 insert into COLLABORATEUR(ROLE,CANDIDAT,EQUIPE,MANAGER) values ('Big Boss',4,null,null);
 insert into COLLABORATEUR(ROLE,CANDIDAT,EQUIPE,MANAGER) values ('Développeur Front',5,null,1);
 insert into COLLABORATEUR(ROLE,CANDIDAT,EQUIPE,MANAGER) values ('Développeur Back',6,null,1);
 insert into COLLABORATEUR(ROLE,CANDIDAT,EQUIPE,MANAGER) values ('Homme à tout faire',7,null,null);

/*
 EQUIPES
 */
 insert into EQUIPE(NOMEQUIPE,MANAGER,COMPETENCES) values ('Le JEE',1,1);
 insert into EQUIPE(NOMEQUIPE,MANAGER,COMPETENCES) values ('La tristesse',4,3);

update COLLABORATEUR set EQUIPE=1 where IDCOLLABORATEUR<4;
update COLLABORATEUR set EQUIPE=2 where IDCOLLABORATEUR=4;

/*
 DEMANDE COMP
 */
 insert into DEMANDECOMPETENCE(COMPETENCE,EQUIPE,FEUXVERTCODIR) values (2,1,1);
 insert into DEMANDECOMPETENCE(COMPETENCE,EQUIPE,FEUXVERTCODIR) values (1,2,0);

/*
 FDP
 */
insert into FICHEDEPOSTE(ARCHIVEE,PRESENTATIONENTREPRISEFDP,PRESENTATIONPOSTEFDP,COMPETENCESFDP) values(0,'La MIAGE est une grande famille','Expert REGEX',2);
insert into FICHEDEPOSTE(ARCHIVEE,PRESENTATIONENTREPRISEFDP,PRESENTATIONPOSTEFDP,COMPETENCESFDP) values(0,'La MIAGE est une grande famille','Expert Word',4);
insert into FICHEDEPOSTE(ARCHIVEE,PRESENTATIONENTREPRISEFDP,PRESENTATIONPOSTEFDP,COMPETENCESFDP) values(1,'La MIAGE est une grande famille','Larbin',1);

/*
 CANDIDATURES
 */
 insert into CANDIDATURE(FICHEDEPOSTE,CANDIDAT,CV,EMAIL,LETTREMOTIVATION,TELEPHONE,DATECANDIDATURE) values (1,2,'Je fais du regex','bob@marlex.fr','je suis motivé','06060606060606',CURRENT DATE);
 insert into CANDIDATURE(FICHEDEPOSTE,CANDIDAT,CV,EMAIL,LETTREMOTIVATION,TELEPHONE,DATECANDIDATURE) values (1,3,'Je fais du tripoux','didier@tripoo.fr','je suis motivé','06060606060606',CURRENT DATE);
 insert into CANDIDATURE(FICHEDEPOSTE,CANDIDAT,CV,EMAIL,LETTREMOTIVATION,TELEPHONE,DATECANDIDATURE) values (2,1,'Je fais du java','ed@monfyon.fr','je suis motivé','06060606060606',CURRENT DATE);

