/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.mirage.lourd.views;

import fr.miage.toulouse.mirage.lourd.controler.MirageControler;
import fr.miage.xfe.mirageshared.interfremote.ExpoLourdeRemote;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

/**
 *
 * @author calme
 */
public class MainFrame extends javax.swing.JFrame {

    private Component dynamicPanel;
    private MirageControler ctrl;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws NamingException {
        initComponents();
        this.dynamicPanel = this.PanelWork;
        
        Context ctx = new InitialContext();
        ExpoLourdeRemote remote = (ExpoLourdeRemote) ctx.lookup("fr.miage.xfe.mirageshared.interfremote.ExpoLourdeRemote");
        this.ctrl = new MirageControler((remote));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        ButtonQuitter = new javax.swing.JButton();
        ButtonCompetences = new javax.swing.JButton();
        ButtonFDP = new javax.swing.JButton();
        ButtonCandidatures = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelWork = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMenu.setBackground(new java.awt.Color(204, 204, 204));
        PanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonQuitter.setText("Quitter");
        ButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuitterActionPerformed(evt);
            }
        });

        ButtonCompetences.setText("Compétences");
        ButtonCompetences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCompetencesActionPerformed(evt);
            }
        });

        ButtonFDP.setText("Créer Fiche de Poste");
        ButtonFDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFDPActionPerformed(evt);
            }
        });

        ButtonCandidatures.setText("Gestion des Candidatures");
        ButtonCandidatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCandidaturesActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\calme\\Documents\\NetBeansProjects\\projetMIRAGE\\mirage-lourd\\Image\\logo.PNG")); // NOI18N

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonCandidatures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonFDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonCompetences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonQuitter)
                .addGap(59, 59, 59))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ButtonCompetences)
                .addGap(33, 33, 33)
                .addComponent(ButtonFDP)
                .addGap(34, 34, 34)
                .addComponent(ButtonCandidatures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonQuitter)
                .addGap(19, 19, 19))
        );

        getContentPane().add(PanelMenu, java.awt.BorderLayout.WEST);

        PanelWork.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelWorkLayout = new javax.swing.GroupLayout(PanelWork);
        PanelWork.setLayout(PanelWorkLayout);
        PanelWorkLayout.setHorizontalGroup(
            PanelWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        PanelWorkLayout.setVerticalGroup(
            PanelWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        getContentPane().add(PanelWork, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonQuitterActionPerformed

    private void ButtonCompetencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCompetencesActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCompetences(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonCompetencesActionPerformed

    private void ButtonFDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFDPActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCreationFDP(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonFDPActionPerformed

    private void ButtonCandidaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCandidaturesActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCandidatures(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonCandidaturesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NamingException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (NamingException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCandidatures;
    private javax.swing.JButton ButtonCompetences;
    private javax.swing.JButton ButtonFDP;
    private javax.swing.JButton ButtonQuitter;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelWork;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
