/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.mirage.lourd.views;

import fr.miage.toulouse.mirage.lourd.controler.MirageControler;
import fr.miage.xfe.mirageshared.utilities.CompetenceExport;
import fr.miage.xfe.mirageshared.utilities.DemandeCompetenceExport;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author calme
 */
public class PanelDemandeConvertor extends javax.swing.JPanel {

    private MirageControler ctrl;
    private DemandeCompetenceExport demandeCompetence;
    
    /**
     * Creates new form PanelFDPCreator
     */
    public PanelDemandeConvertor(int idCompetence,int idEquipe,MirageControler ctrl) {
        initComponents();
        this.ctrl = ctrl;
        if(this.ctrl.getDemandeCompetence(idCompetence, idEquipe)!=null){
            this.demandeCompetence = this.ctrl.getDemandeCompetence(idCompetence, idEquipe);
            fillCompetences();
        }else{
            this.setVisible(false);
            javax.swing.JOptionPane.showMessageDialog(this,"Erreur Demande introuvable");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelEntreprise = new javax.swing.JScrollPane();
        TxtEntreprise = new javax.swing.JTextArea();
        PanelPoste = new javax.swing.JScrollPane();
        TxtPoste = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelCompetence = new javax.swing.JLabel();
        ButtonAnnuler = new javax.swing.JButton();
        ButtonValider = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(854, 712));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Demande Convertor");

        TxtEntreprise.setColumns(20);
        TxtEntreprise.setRows(5);
        PanelEntreprise.setViewportView(TxtEntreprise);

        TxtPoste.setColumns(20);
        TxtPoste.setRows(5);
        PanelPoste.setViewportView(TxtPoste);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Description de l'entreprise");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Description du poste");

        LabelCompetence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ButtonAnnuler.setText("Annuler");
        ButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnnulerActionPerformed(evt);
            }
        });

        ButtonValider.setText("Valider");
        ButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(PanelEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                            .addComponent(PanelPoste)
                            .addComponent(jLabel3)
                            .addComponent(LabelCompetence)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(ButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(ButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(PanelPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(LabelCompetence)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnnulerActionPerformed
        ((JFrame)getParent().getParent().getParent().getParent()).dispose();
    }//GEN-LAST:event_ButtonAnnulerActionPerformed

    private void ButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonValiderActionPerformed
        String presentationPoste = this.TxtPoste.getText();
        String presentationEntreprise = this.TxtEntreprise.getText();
        if(!"".equals(presentationEntreprise) && !"".equals(presentationPoste)){
            this.ctrl.convertirDemandeCompetence(this.demandeCompetence, presentationPoste, presentationEntreprise);
            ((JFrame)getParent().getParent().getParent().getParent()).dispose();          
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Erreur: Formulaire incomplet");            
        }
    }//GEN-LAST:event_ButtonValiderActionPerformed

    private void fillCompetences(){
        String donnee = this.demandeCompetence.getCompetence().getNomCompetence();
        this.LabelCompetence.setText("Compétence: " + donnee);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnnuler;
    private javax.swing.JButton ButtonValider;
    private javax.swing.JLabel LabelCompetence;
    private javax.swing.JScrollPane PanelEntreprise;
    private javax.swing.JScrollPane PanelPoste;
    private javax.swing.JTextArea TxtEntreprise;
    private javax.swing.JTextArea TxtPoste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
