/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.mirage.lourd.views;

import fr.miage.toulouse.mirage.lourd.controler.MirageControler;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author calme
 */
public class PanelCompetences extends javax.swing.JPanel {

    private Component dynamicPanel;
    private MirageControler ctrl;
    
    /**
     * Creates new form PanelCompetences
     */
    public PanelCompetences(MirageControler ctrl) {
        initComponents();
        this.dynamicPanel = PanelDisplay;
        this.ctrl = ctrl;
        initTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonEquipe = new javax.swing.JButton();
        ButtonCollab = new javax.swing.JButton();
        ButtonToutes = new javax.swing.JButton();
        PanelDisplay = new javax.swing.JPanel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(854, 712));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Liste des Compétences");

        ButtonEquipe.setText("Par équipes");
        ButtonEquipe.setMaximumSize(new java.awt.Dimension(119, 23));
        ButtonEquipe.setMinimumSize(new java.awt.Dimension(119, 23));
        ButtonEquipe.setPreferredSize(new java.awt.Dimension(119, 23));
        ButtonEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEquipeActionPerformed(evt);
            }
        });

        ButtonCollab.setText("Par collaborateurs");
        ButtonCollab.setPreferredSize(new java.awt.Dimension(119, 23));
        ButtonCollab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCollabActionPerformed(evt);
            }
        });

        ButtonToutes.setText("Toutes");
        ButtonToutes.setMaximumSize(new java.awt.Dimension(119, 23));
        ButtonToutes.setMinimumSize(new java.awt.Dimension(119, 23));
        ButtonToutes.setPreferredSize(new java.awt.Dimension(119, 23));
        ButtonToutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToutesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(ButtonToutes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCollab, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ButtonEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCollab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonToutes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        add(PanelHeader, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout PanelDisplayLayout = new javax.swing.GroupLayout(PanelDisplay);
        PanelDisplay.setLayout(PanelDisplayLayout);
        PanelDisplayLayout.setHorizontalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        PanelDisplayLayout.setVerticalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        add(PanelDisplay, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEquipeActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCompetencesEquipes(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonEquipeActionPerformed

    private void ButtonToutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToutesActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCompetencesToutes(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonToutesActionPerformed

    private void ButtonCollabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCollabActionPerformed
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCompetencesCollabs(this.ctrl));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ButtonCollabActionPerformed

    private void initTab(){
        this.remove(this.dynamicPanel);
        this.dynamicPanel = this.add(new PanelCompetencesToutes(this.ctrl));
        this.revalidate();
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCollab;
    private javax.swing.JButton ButtonEquipe;
    private javax.swing.JButton ButtonToutes;
    private javax.swing.JPanel PanelDisplay;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
