/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.mirage.lourd.views;

import fr.miage.toulouse.mirage.lourd.controler.MirageControler;
import fr.miage.toulouse.mirage.lourd.others.TableFunctions;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.beans.PropertyChangeListener;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.MouseInputListener;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author calme
 */
public class PanelListeCandidatures extends javax.swing.JPanel {

    private MirageControler ctrl;
    
    /**
     * Creates new form PanelListeCandidatures
     */
    public PanelListeCandidatures(MirageControler ctrl) {
        initComponents();
        this.ctrl = ctrl;
        fillTable();
    }
    
    private void fillTable(){
        Object[][] donnees = this.ctrl.getAllFDP();
        
        String[] entetes = {"ID FDP", "Présentation du poste", "Présentation de l'équipe","Nb Candidats"};
        JTable tableau = new JTable(donnees, entetes);
        
        
        tableau.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        TableFunctions.formatTable(tableau);
        
        
        tableau.addMouseListener(new MouseInputListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int index = tableau.getSelectedRow();
                if(tableau.getModel().getRowCount()>=index){
                    int ID = (int)tableau.getModel().getValueAt(index, 0);
                    openFDP(ID);
                }
            }
            @Override
            public void mousePressed(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseExited(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseDragged(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void mouseMoved(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        
        this.add(tableau.getTableHeader(),BorderLayout.NORTH);
        this.add(new JScrollPane(tableau),BorderLayout.CENTER); 
        
    }
    
    private void openFDP(int id){
        JFrame frameFDP = new JFrame("FDP " + id);
        frameFDP.add(new PanelFDP(id,this.ctrl));
        frameFDP.setVisible(true);
        frameFDP.pack();
        frameFDP.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frameFDP.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                removeAll();
                System.out.println("LOL");
                fillTable();
                revalidate();
                repaint();
                frameFDP.dispose();
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(848, 606));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}