/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.miage.toulouse.mirage.lourd.views;

import fr.miage.toulouse.mirage.lourd.controler.MirageControler;
import fr.miage.toulouse.mirage.lourd.others.TableFunctions;
import fr.miage.xfe.mirageshared.utilities.CandidatureExport;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Formattable;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author calme
 */
public class PanelCandidat extends javax.swing.JPanel {

    private MirageControler ctrl;
    private CandidatureExport candidature;
    
    /**
     * Creates new form PanelCandidat
     */
    public PanelCandidat(CandidatureExport candidature,MirageControler ctrl) {
        initComponents();
        this.ctrl = ctrl;
        this.candidature = candidature;
        fillCandidat();
    }

    private void fillCandidat(){
        Object[][] candidat = this.ctrl.getCandidatInformation(candidature);
        String[] entetes = {"ID","Prénom","Nom","Compétences"};
        JTable tabCandidat = new JTable(candidat, entetes);
        TableFunctions.formatTable(tabCandidat);
        tabCandidat.setEnabled(false);
        JButton buttonConcretiser = new JButton("Concrétiser");
        buttonConcretiser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String response = JOptionPane.showInputDialog(null,"Entrez le rôle", "Role", JOptionPane.QUESTION_MESSAGE);
                if(response!="")
                    ctrl.concretiser(candidature.getCandidat(), response);
                else
                    javax.swing.JOptionPane.showMessageDialog(null,"Erreur: aucun rôle n'a été saisi!");
                    
            }
        });
        buttonConcretiser.setEnabled((boolean)candidat[0][candidat[0].length-1]);
        JButton buttonSupprimer = new JButton("Supprimer");
        buttonSupprimer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ctrl.removeCandidature(candidature);
                javax.swing.JOptionPane.showMessageDialog(null,"Candidat supprimé");
                setVisible(false);
            }
        });
        JPanel panTab = new JPanel(new BorderLayout());
        panTab.add(tabCandidat.getTableHeader(),BorderLayout.NORTH);
        panTab.add(tabCandidat,BorderLayout.CENTER);
        this.add(panTab);
        this.add(buttonConcretiser);
        this.add(buttonSupprimer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
